steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: '/'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'functions', 'deploy', 'app', '--gen2','--trigger-http', '--runtime', 'nodejs16', '--entry-point', 'app', '--region', 'us-central1']
    dir: '/'
